// <auto-generated />
using System;
using IHolder.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IHolder.Data.Migrations
{
    [DbContext(typeof(IHolderContext))]
    [Migration("20200422150755_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IHolder.Business.Entities.Aporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Ativo_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Data_alteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_aporte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_inclusao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Preco_medio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Preco_total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Usuario_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Ativo_id");

                    b.HasIndex("Usuario_id");

                    b.ToTable("Aporte");
                });

            modelBuilder.Entity("IHolder.Business.Entities.Ativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caracteristicas")
                        .IsRequired()
                        .HasColumnType("VARCHAR(240)");

                    b.Property<decimal>("Cotacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Data_inclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<Guid>("Produto_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Risco")
                        .HasColumnType("TINYINT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<Guid>("Usuario_inclusao_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Produto_id");

                    b.HasIndex("Usuario_inclusao_id");

                    b.ToTable("Ativo");
                });

            modelBuilder.Entity("IHolder.Business.Entities.Distribuicao_por_ativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Ativo_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Data_alteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_inclusao")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Orientacao")
                        .HasColumnType("TINYINT");

                    b.Property<decimal>("Percentual_atual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Percentual_diferenca")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Percentual_objetivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Usuario_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor_atual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor_diferenca")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo_id");

                    b.HasIndex("Usuario_id");

                    b.ToTable("Distribuicao_por_ativo");
                });

            modelBuilder.Entity("IHolder.Business.Entities.Distribuicao_por_produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Data_alteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_inclusao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Distribuicao_por_tipo_investimento_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Orientacao")
                        .HasColumnType("TINYINT");

                    b.Property<decimal>("Percentual_atual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Percentual_diferenca")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Percentual_objetivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Produto_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Usuario_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor_atual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor_diferenca")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Distribuicao_por_tipo_investimento_id");

                    b.HasIndex("Produto_id");

                    b.HasIndex("Usuario_id");

                    b.ToTable("Distribuicao_por_produto");
                });

            modelBuilder.Entity("IHolder.Business.Entities.Distribuicao_por_tipo_investimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Data_alteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_inclusao")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Orientacao")
                        .HasColumnType("TINYINT");

                    b.Property<decimal>("Percentual_atual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Percentual_diferenca")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Percentual_objetivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Tipo_investimento_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Usuario_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor_atual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor_diferenca")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Tipo_investimento_id");

                    b.HasIndex("Usuario_id");

                    b.ToTable("Distribuicao_por_tipo_investimento");
                });

            modelBuilder.Entity("IHolder.Business.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caracteristicas")
                        .IsRequired()
                        .HasColumnType("VARCHAR(240)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<Guid>("Tipo_investimento_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Tipo_investimento_id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("IHolder.Business.Entities.Situacao_por_ativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Ativo_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Data_alteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_inclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacao")
                        .HasColumnType("VARCHAR(240)");

                    b.Property<byte>("Situacao")
                        .HasColumnType("TINYINT");

                    b.Property<Guid>("Usuario_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Ativo_id");

                    b.HasIndex("Usuario_id");

                    b.ToTable("Situacao_por_ativo");
                });

            modelBuilder.Entity("IHolder.Business.Entities.Tipo_investimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caracteristicas")
                        .IsRequired()
                        .HasColumnType("VARCHAR(240)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<byte>("Risco")
                        .HasColumnType("TINYINT");

                    b.HasKey("Id");

                    b.ToTable("Tipo_investimento");
                });

            modelBuilder.Entity("IHolder.Business.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.Property<DateTime?>("Data_alteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_inclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(40)");

                    b.Property<byte>("Genero")
                        .HasColumnType("TINYINT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(80)");

                    b.Property<string>("Senha")
                        .HasColumnType("VARCHAR(240)");

                    b.HasKey("Id");

                    b.HasAlternateKey("CPF");

                    b.HasAlternateKey("Celular");

                    b.HasAlternateKey("Email");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("IHolder.Business.Entities.Aporte", b =>
                {
                    b.HasOne("IHolder.Business.Entities.Ativo", "Ativo")
                        .WithMany("Aportes")
                        .HasForeignKey("Ativo_id")
                        .IsRequired();

                    b.HasOne("IHolder.Business.Entities.Usuario", "Usuario")
                        .WithMany("Aportes")
                        .HasForeignKey("Usuario_id")
                        .IsRequired();
                });

            modelBuilder.Entity("IHolder.Business.Entities.Ativo", b =>
                {
                    b.HasOne("IHolder.Business.Entities.Produto", "Produto")
                        .WithMany("Ativos")
                        .HasForeignKey("Produto_id")
                        .IsRequired();

                    b.HasOne("IHolder.Business.Entities.Usuario", "Usuario_inclusao")
                        .WithMany("Ativos")
                        .HasForeignKey("Usuario_inclusao_id")
                        .IsRequired();
                });

            modelBuilder.Entity("IHolder.Business.Entities.Distribuicao_por_ativo", b =>
                {
                    b.HasOne("IHolder.Business.Entities.Ativo", "Ativo")
                        .WithMany("Distribuicoes_por_ativos")
                        .HasForeignKey("Ativo_id")
                        .IsRequired();

                    b.HasOne("IHolder.Business.Entities.Usuario", "Usuario")
                        .WithMany("Distribuicoes_por_ativos")
                        .HasForeignKey("Usuario_id")
                        .IsRequired();
                });

            modelBuilder.Entity("IHolder.Business.Entities.Distribuicao_por_produto", b =>
                {
                    b.HasOne("IHolder.Business.Entities.Distribuicao_por_tipo_investimento", "Distribuicao_por_tipo_investimento")
                        .WithMany("Distribuicoes_por_produtos")
                        .HasForeignKey("Distribuicao_por_tipo_investimento_id")
                        .IsRequired();

                    b.HasOne("IHolder.Business.Entities.Produto", "Produto")
                        .WithMany("Distribuicoes_por_produtos")
                        .HasForeignKey("Produto_id")
                        .IsRequired();

                    b.HasOne("IHolder.Business.Entities.Usuario", "Usuario")
                        .WithMany("Distribuicoes_por_produtos")
                        .HasForeignKey("Usuario_id")
                        .IsRequired();
                });

            modelBuilder.Entity("IHolder.Business.Entities.Distribuicao_por_tipo_investimento", b =>
                {
                    b.HasOne("IHolder.Business.Entities.Tipo_investimento", "Tipo_investimento")
                        .WithMany("Distribuicoes_por_tipos_investimentos")
                        .HasForeignKey("Tipo_investimento_id")
                        .IsRequired();

                    b.HasOne("IHolder.Business.Entities.Usuario", "Usuario")
                        .WithMany("Distribuicoes_por_tipos_investimentos")
                        .HasForeignKey("Usuario_id")
                        .IsRequired();
                });

            modelBuilder.Entity("IHolder.Business.Entities.Produto", b =>
                {
                    b.HasOne("IHolder.Business.Entities.Tipo_investimento", "Tipo_investimento")
                        .WithMany("Produtos")
                        .HasForeignKey("Tipo_investimento_id")
                        .IsRequired();
                });

            modelBuilder.Entity("IHolder.Business.Entities.Situacao_por_ativo", b =>
                {
                    b.HasOne("IHolder.Business.Entities.Ativo", "Ativo")
                        .WithMany("Situacoes_por_ativos")
                        .HasForeignKey("Ativo_id")
                        .IsRequired();

                    b.HasOne("IHolder.Business.Entities.Usuario", "Usuario")
                        .WithMany("Situacoes_por_ativos")
                        .HasForeignKey("Usuario_id")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
